const generateGiftSets = require('./combinaciones')

test('Test: return type',() => {
    expect(
        Array.isArray(generateGiftSets(['car', 'doll', 'puzzle'])))
        .toBe(true)
})

test(`Test: generateGiftSets(['car'])`, () => {
    expect(
        generateGiftSets(['car'])
    ).toStrictEqual(
        [
            [
              "car"
            ]
        ]
    )
})

test(`Test: generateGiftSets(['car','doll'])`, () => {
    expect(
        generateGiftSets(['car','doll'])
    ).toStrictEqual(
        [
            [
              "car"
            ],
            [
              "doll"
            ],
            [
              "car",
              "doll"
            ]
        ]
    )
})

test(`Test: generateGiftSets(['car','doll','puzzle'])`, () => {
    expect(
        generateGiftSets(['car','doll','puzzle'])
    ).toStrictEqual(
        [
            [
              "car"
            ],
            [
              "doll"
            ],
            [
              "puzzle"
            ],
            [
              "car",
              "doll"
            ],
            [
              "car",
              "puzzle"
            ],
            [
              "doll",
              "puzzle"
            ],
            [
              "car",
              "doll",
              "puzzle"
            ]
        ]
    )
})

test(`Test: generateGiftSets(['apple', 'banana', 'cherry', 'date'])`, () => {
    expect(
        generateGiftSets(['apple', 'banana', 'cherry', 'date'])
    ).toStrictEqual(
        [
            [
              "apple"
            ],
            [
              "banana"
            ],
            [
              "cherry"
            ],
            [
              "date"
            ],
            [
              "apple",
              "banana"
            ],
            [
              "apple",
              "cherry"
            ],
            [
              "apple",
              "date"
            ],
            [
              "banana",
              "cherry"
            ],
            [
              "banana",
              "date"
            ],
            [
              "cherry",
              "date"
            ],
            [
              "apple",
              "banana",
              "cherry"
            ],
            [
              "apple",
              "banana",
              "date"
            ],
            [
              "apple",
              "cherry",
              "date"
            ],
            [
              "banana",
              "cherry",
              "date"
            ],
            [
              "apple",
              "banana",
              "cherry",
              "date"
            ]
        ]
    )
})

test(`Test: generateGiftSets(['pen', 'notebook', 'eraser', 'pencil', 'marker'])`, () => {
    expect(
        generateGiftSets(['pen', 'notebook', 'eraser', 'pencil', 'marker'])
    ).toStrictEqual(
        [
            [
              "pen"
            ],
            [
              "notebook"
            ],
            [
              "eraser"
            ],
            [
              "pencil"
            ],
            [
              "marker"
            ],
            [
              "pen",
              "notebook"
            ],
            [
              "pen",
              "eraser"
            ],
            [
              "pen",
              "pencil"
            ],
            [
              "pen",
              "marker"
            ],
            [
              "notebook",
              "eraser"
            ],
            [
              "notebook",
              "pencil"
            ],
            [
              "notebook",
              "marker"
            ],
            [
              "eraser",
              "pencil"
            ],
            [
              "eraser",
              "marker"
            ],
            [
              "pencil",
              "marker"
            ],
            [
              "pen",
              "notebook",
              "eraser"
            ],
            [
              "pen",
              "notebook",
              "pencil"
            ],
            [
              "pen",
              "notebook",
              "marker"
            ],
            [
              "pen",
              "eraser",
              "pencil"
            ],
            [
              "pen",
              "eraser",
              "marker"
            ],
            [
              "pen",
              "pencil",
              "marker"
            ],
            [
              "notebook",
              "eraser",
              "pencil"
            ],
            [
              "notebook",
              "eraser",
              "marker"
            ],
            [
              "notebook",
              "pencil",
              "marker"
            ],
            [
              "eraser",
              "pencil",
              "marker"
            ],
            [
              "pen",
              "notebook",
              "eraser",
              "pencil"
            ],
            [
              "pen",
              "notebook",
              "eraser",
              "marker"
            ],
            [
              "pen",
              "notebook",
              "pencil",
              "marker"
            ],
            [
              "pen",
              "eraser",
              "pencil",
              "marker"
            ],
            [
              "notebook",
              "eraser",
              "pencil",
              "marker"
            ],
            [
              "pen",
              "notebook",
              "eraser",
              "pencil",
              "marker"
            ]
        ]
    )
})

test(`Test: generateGiftSets([])`, () => {
    expect(
        generateGiftSets([])
    ).toStrictEqual(
        []
    )
})